---
title: "Homework 3 - deg2163"
author: "Diana Ballesteros Gonzalez"
date: "10/11/2018"
output: github_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# ***Problem 1*** 
```{r setup_problem_1}
# install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")

## loading the library and obtaining data
library(p8105.datasets)
data("brfss_smart2010")
```

```{r brfss_smart_2010_df}
## cleaning the dataset 
brfss_smart2010_clean = 
   brfss_smart2010 %>% 
   janitor::clean_names() %>% 
   rename(state = locationabbr, county = locationdesc) %>% 
   filter(topic == "Overall Health" & (response == "Excellent" | response == "Very good" |
                                       response == "Good" | response == "Fair" | 
                                       response == "Poor")) %>% 
   mutate(response = ordered(response, levels = c("Poor", "Fair", "Good", "Very good", "Excellent")))
```

```{r problem_1_questions}
## In 2002, which states were observed at 7 locations? Answer: CT, FL, and NC
brfss_smart2010_clean %>% 
  filter(year == 2002) %>% 
  group_by(state) %>% 
  distinct(county) %>% 
  count() %>% 
  filter(n == 7) 
```

```{r spaghett_plot}
## Make a “spaghetti plot” that shows the number of locations in each state from 2002 to 2010.
brfss_smart2010_clean %>% 
  group_by(state, year) %>% 
  distinct(county) %>%
  summarize(count_county = n()) %>% 
  ggplot(aes(x = year, y = count_county, color = state)) + 
  geom_line() + 
  labs(
    title = "Number of locations in each state from 2002 to 2010",
    x = "Year",
    y = "Number of locations in each state",
    caption = "Data from the brfss_smart2010 package"
  ) + 
  viridis::scale_color_viridis(
    name = "States", 
    discrete = TRUE) + 
  theme_bw() 
```

```{r table_mean_sd}
## ## Make a table showing, for the years 2002, 2006, and 2010, the mean and standard deviation of the proportion of “Excellent” responses across locations in NY State. 
## SD I keep getting NA, need to convert from percentage to prop
brfss_smart2010_clean %>% 
  filter((year == 2002 | year == 2006 | year == 2010) & (state == "NY") 
         & response == "Excellent") %>% 
  group_by(year, state, county) %>% 
  spread(key = response, value = data_value) %>%
  janitor::clean_names() %>% 
  summarize(mean_excellent = mean(excellent),
            sd_excellent = sd(excellent)) %>% 
  knitr::kable()
```

```{r}
## For each year and state, compute the average proportion in each response category (taking the average across locations in a state). Make a five-panel plot that shows, for each response category separately, the distribution of these state-level averages over time.
brfss_smart2010_clean %>% 
  group_by(year, state, response) %>% 
  summarize(mean_response_category = mean(data_value/100)) %>% 
  ggplot(aes(x = year, y = mean_response_category, color = state)) + 
  geom_line() + 
  facet_grid(~response) + 
  labs(
    title = "Distribution of state-level averages over time",
    x = "Year",
    y = "Average proportion in each response category",
    caption = "Data from the brfss_smart2010 dataset"
  ) + 
  viridis::scale_color_viridis(
    name = "State", 
    discrete = TRUE
  )
```

